- name: copy file 
  copy:
   src: answer.txt
   dest: "{{ path_to_file }}" 
   group: root
   owner: root
   mode: 0555
 

- name: add line to file
  tags: jinn,sometext
  lineinfile:
    path: "{{ path_to_file }}" 
    regexp: '^Provoking'
    line: KEFTEME
  when: ansible_distribution == "CentOS"
  notify: answer


 
