---

- hosts: all
  tasks:

  - name: install vim
    tags: vim
    package:
      name:
        - "{{ vim_package }}"
        - "{{ wget_package }}"
      state: latest
      update_cache: yes
    environment:
      http_proxy: http://proxy.infosec.ru:8080
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

- hosts: all
  roles:
    - base

- hosts: jinn_hosts
  roles:
    - jinn_servers

- hosts: urp_hosts
  roles:
    - urp_servers


