---

- hosts: all
  tasks:

  - name: update
    yum:
      update_cache: true
  - name: install vim
    yum:
      name: vim
      state: latest
    environment:
      http_proxy: http://proxy.infosec.ru:8080
